name: Run tests on MariaDB

on:
  push:
    branches: [ master ]
    paths:
      - '**.py'
      - .github/workflows/tests-mariadb.yml
      - requirements-test.txt
  pull_request:
    branches: [ master ]

jobs:
  tests-mariadb:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.7, 3.8, 3.9, pypy-3.7-v7.3.3]
    env:
      OS: ubuntu-latest
      PYTHON: ${{ matrix.python-version }}
    services:
      mysql:
        image: mariadb
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
          MARIADB_DATABASE: tests
        ports:
          - 3333:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Verify MariaDB connection
      run: |
        while ! mysqladmin ping -h"127.0.0.1" -P"3333" --silent; do
          sleep 1
        done
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install MariaDB
      run: |
        sudo apt-get install mariadb-server
        mysqld --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
    - name: Run test
      run: |
        pytest --mysql-user=$USER -n 0 -k "not mysqlnoproc" --cov-report=xml
    - name: Run xdist test
      run: |
        pytest --mysql-user=$USER -n 1 -k "not mysqlnoproc" --cov-report=xml:coverage-xdist.xml
    - name: Run noproc test
      run: |
        pytest -n 0 -k mysqlnoproc --cov-report=xml:coverage-noproc.xml --mysql-host="127.0.0.1" --mysql-port=3333
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
#        files: ./coverage.xml, ./coverage-xdist.xml, ./coverage-noproc.xml
        flags: linux,mariadb
        env_vars: OS, PYTHON
        fail_ci_if_error: true
